#!/bin/bash

 ##############################################################################
 #                                                                            #
 # Copyright (C) 2022 MachineWare GmbH                                        #
 # All Rights Reserved                                                        #
 #                                                                            #
 # This is work is licensed under the terms described in the LICENSE file     #
 # found in the root directory of this source tree.                           #
 #                                                                            #
 ##############################################################################


home="$(cd $(dirname $(dirname ${BASH_SOURCE[0]} )) &>/dev/null && pwd)"
formatter="$home/cmake/Tools/$(uname -s)/clang-format-15.$(arch)"
srcdirs="$home/src $home/include $home/test"
sources=$(find $srcdirs -name '*.h' -or -name '*.cpp' | grep -v googletest)
exec $formatter --Werror $sources $@
