#!/bin/bash

 ##############################################################################
 #                                                                            #
 # Copyright 2023 MachineWare GmbH                                            #
 #                                                                            #
 # Licensed under the Apache License, Version 2.0 (the "License");            #
 # you may not use this file except in compliance with the License.           #
 # You may obtain a copy of the License at                                    #
 #                                                                            #
 #     http://www.apache.org/licenses/LICENSE-2.0                             #
 #                                                                            #
 # Unless required by applicable law or agreed to in writing, software        #
 # distributed under the License is distributed on an "AS IS" BASIS,          #
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
 # See the License for the specific language governing permissions and        #
 # limitations under the License.                                             #
 #                                                                            #
 ##############################################################################

home="$(cd $(dirname $(dirname ${BASH_SOURCE[0]} )) &>/dev/null && pwd)"
formatter="$home/cmake/Tools/$(uname -s)/clang-format-15.$(arch)"
srcdirs="$home/src $home/include $home/test"
sources=$(find $srcdirs -name '*.h' -or -name '*.cpp' | grep -v googletest)
exec $formatter --Werror $sources $@
